# Generated by Django 4.2.5 on 2023-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_image_place2_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='place2',
            name='relation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
